### ISSUE TITLE
请问这个开源项目是不是有对应的论文鸭

### ISSUE THREAD

**Issue by Arashiailing** [u21h2/AutoSpear#3]
师傅你好 因为关注太久了忘了是那篇论文 感觉应该是论文里来关注的项目 如果有的话请问可以放一下论文链接吗

**Comment by u21h2** [comment]
是有个talk吧 https://blackhat.com/asia-22/briefings/schedule/index.html#autospear-towards-automatically-bypassing-and-inspecting-web-application-firewalls-25503

**Comment by Arashiailing** [comment]
是的是的 感谢师傅
